version: "3.9"

services:
  postgres:
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
    volumes:
        - ./data/db:/var/lib/postgresql/data
    restart: unless-stopped