"""added read and write addresses fields in controller model

Revision ID: f231b589d550
Revises: e3164fb9df0e
Create Date: 2024-05-28 22:24:47.623855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f231b589d550'
down_revision: Union[str, None] = 'e3164fb9df0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'controllers', sa.Column(
            'read_address', sa.Integer(), nullable=True

        )
    )
    op.add_column(
        'controllers', sa.Column(
            'write_address', sa.Integer(), nullable=True
        )
    )
    op.execute('UPDATE controllers SET read_address = 0, write_address = 1')
    op.alter_column('controllers', 'read_address', nullable=False)
    op.alter_column('controllers', 'write_address', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('controllers', 'write_address')
    op.drop_column('controllers', 'read_address')
    # ### end Alembic commands ###
