"""Added user_id to the controllers table

Revision ID: e3164fb9df0e
Revises: a534eb1eef84
Create Date: 2024-01-08 14:56:18.601255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3164fb9df0e'
down_revision: Union[str, None] = 'a534eb1eef84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controllers', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'controllers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'controllers', type_='foreignkey')
    op.drop_column('controllers', 'user_id')
    # ### end Alembic commands ###
