"""added low and high limit fields in controller model

Revision ID: 61730e38ef88
Revises: f231b589d550
Create Date: 2024-05-28 22:52:03.723696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61730e38ef88'
down_revision: Union[str, None] = 'f231b589d550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'controllers', sa.Column(
            'low_limit', sa.Integer(), nullable=True
        )
    )
    op.add_column(
        'controllers', sa.Column(
            'high_limit', sa.Integer(), nullable=True
        )
    )
    op.execute("UPDATE controllers SET low_limit = 0, high_limit = 65535")
    op.alter_column('controllers', 'low_limit', nullable=False)
    op.alter_column('controllers', 'high_limit', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('controllers', 'high_limit')
    op.drop_column('controllers', 'low_limit')
    # ### end Alembic commands ###
